#!/bin/bash
#
#-----------------------------------------------------------------------------

surfaceTransformPoints -translate "(0  1.619148349104671e-01 0)" \
    constant/triSurface/rollerOrig.stl constant/triSurface/roller.stl
