#!/bin/bash
#
#-----------------------------------------------------------------------------

surfaceTransformPoints -translate "(0  1.623269822252245e-01 0)" \
    constant/triSurface/rollerOrig.stl constant/triSurface/roller.stl
