#!/bin/bash
#
#-----------------------------------------------------------------------------

surfaceTransformPoints -translate "(0  1.500000000000000e-01 0)" \
    constant/triSurface/rollerOrig.stl constant/triSurface/roller.stl
