#!/bin/bash
#
#-----------------------------------------------------------------------------

surfaceTransformPoints -translate "(0  1.614999468701567e-01 0)" \
    constant/triSurface/rollerOrig.stl constant/triSurface/roller.stl
