#!/bin/bash
#
#-----------------------------------------------------------------------------

surfaceTransformPoints -translate "(0  1.616187525979624e-01 0)" \
    constant/triSurface/rollerOrig.stl constant/triSurface/roller.stl
