#!/bin/bash
#
#-----------------------------------------------------------------------------

surfaceTransformPoints -translate "(0  1.618241301628461e-01 0)" \
    constant/triSurface/rollerOrig.stl constant/triSurface/roller.stl
