#!/bin/bash
#
#-----------------------------------------------------------------------------

surfaceTransformPoints -translate "(0  1.620182936347235e-01 0)" \
    constant/triSurface/rollerOrig.stl constant/triSurface/roller.stl
