#!/bin/bash
#
#-----------------------------------------------------------------------------

surfaceTransformPoints -translate "(0  1.625090632849076e-01 0)" \
    constant/triSurface/rollerOrig.stl constant/triSurface/roller.stl
