#!/bin/bash
#
#-----------------------------------------------------------------------------

surfaceTransformPoints -translate "(0  1.637854657393402e-01 0)" \
    constant/triSurface/rollerOrig.stl constant/triSurface/roller.stl
