#!/bin/bash
#
#-----------------------------------------------------------------------------

surfaceTransformPoints -translate "(0  1.611826573320801e-01 0)" \
    constant/triSurface/rollerOrig.stl constant/triSurface/roller.stl
