#!/bin/bash
#
#-----------------------------------------------------------------------------

surfaceTransformPoints -translate "(0  1.625855620163197e-01 0)" \
    constant/triSurface/rollerOrig.stl constant/triSurface/roller.stl
