#!/bin/bash
#
#-----------------------------------------------------------------------------

surfaceTransformPoints -translate "(0  1.640007825047424e-01 0)" \
    constant/triSurface/rollerOrig.stl constant/triSurface/roller.stl
