#!/bin/bash
#
#-----------------------------------------------------------------------------

surfaceTransformPoints -translate "(0  1.615499240866153e-01 0)" \
    constant/triSurface/rollerOrig.stl constant/triSurface/roller.stl
