#!/bin/bash
#
#-----------------------------------------------------------------------------

surfaceTransformPoints -translate "(0  1.614877677823004e-01 0)" \
    constant/triSurface/rollerOrig.stl constant/triSurface/roller.stl
