#!/bin/bash
#
#-----------------------------------------------------------------------------

surfaceTransformPoints -translate "(0  1.697403979923865e-01 0)" \
    constant/triSurface/rollerOrig.stl constant/triSurface/roller.stl
