#!/bin/bash
#
#-----------------------------------------------------------------------------

surfaceTransformPoints -translate "(0  1.610548308769786e-01 0)" \
    constant/triSurface/rollerOrig.stl constant/triSurface/roller.stl
