#!/bin/bash
#
#-----------------------------------------------------------------------------

surfaceTransformPoints -translate "(0  1.613769758391571e-01 0)" \
    constant/triSurface/rollerOrig.stl constant/triSurface/roller.stl
