#!/bin/bash
#
#-----------------------------------------------------------------------------

surfaceTransformPoints -translate "(0  1.525764472302881e-01 0)" \
    constant/triSurface/rollerOrig.stl constant/triSurface/roller.stl
