#!/bin/bash
#
#-----------------------------------------------------------------------------

surfaceTransformPoints -translate "(0  1.609427593926353e-01 0)" \
    constant/triSurface/rollerOrig.stl constant/triSurface/roller.stl
