#!/bin/bash
#
#-----------------------------------------------------------------------------

surfaceTransformPoints -translate "(0  1.605313261919609e-01 0)" \
    constant/triSurface/rollerOrig.stl constant/triSurface/roller.stl
