#!/bin/bash
#
#-----------------------------------------------------------------------------

surfaceTransformPoints -translate "(0  1.616540669453755e-01 0)" \
    constant/triSurface/rollerOrig.stl constant/triSurface/roller.stl
