#!/bin/bash
#
#-----------------------------------------------------------------------------

surfaceTransformPoints -translate "(0  1.620780068688917e-01 0)" \
    constant/triSurface/rollerOrig.stl constant/triSurface/roller.stl
