#!/bin/bash
#
#-----------------------------------------------------------------------------

surfaceTransformPoints -translate "(0  1.615634203375622e-01 0)" \
    constant/triSurface/rollerOrig.stl constant/triSurface/roller.stl
