#!/bin/bash
#
#-----------------------------------------------------------------------------

surfaceTransformPoints -translate "(0  1.618949804774199e-01 0)" \
    constant/triSurface/rollerOrig.stl constant/triSurface/roller.stl
